# Generated by Django 4.1 on 2022-09-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='level_id',
            new_name='level',
        ),
    ]
