# Generated by Django 4.1 on 2022-09-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_rename_level_id_picture_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='user_id',
            new_name='user',
        ),
    ]
