# Generated by Django 4.1 on 2022-09-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_rename_user_id_video_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
