# Generated by Django 4.1 on 2022-09-06 06:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0005_socre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Socre',
            new_name='Score',
        ),
        migrations.RenameField(
            model_name='score',
            old_name='scorepoints',
            new_name='points',
        ),
    ]
