# Generated by Django 4.1 on 2022-09-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_rename_socre_score_rename_scorepoints_score_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
