# Generated by Django 4.1 on 2022-09-06 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_alter_video_user_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user',
            new_name='user_id',
        ),
    ]
