# Generated by Django 4.1 on 2022-09-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_rename_user_score_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='user_id',
            new_name='user',
        ),
    ]
