# Generated by Django 4.1 on 2022-09-06 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_rename_user_id_score_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='points',
            new_name='guessed',
        ),
        migrations.AddField(
            model_name='score',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
