<<<<<<< HEAD
# Generated by Django 4.1.1 on 2022-09-10 12:16
=======
# Generated by Django 4.1.1 on 2022-09-10 14:08
>>>>>>> bug_fix_branch

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_rename_points_score_guessed_score_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.FloatField(),
        ),
    ]
