# Generated by Django 4.1 on 2022-09-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_rename_points_score_guessed_score_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.CharField(max_length=255),
        ),
    ]
