version: '2'
services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blank
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/mysql:/var/lib/mysql
  web:
    build: ./web/.
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=blank
      - DB_ROOT_PASSWORD=root
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080